### ISSUE TITLE
開発環境をDocker対応

### ISSUE THREAD

**Issue by nobmurakami** [nobmurakami/my-game-db#132]
参考：
https://qiita.com/y-suna/items/e52b3af1d80c52b66b31

# ToDo
- [x] Dockerfileを作成
- [x] docker-compose.ymlを作成
- [x] config/database.ymlの`default`に、docker-compose.ymlに記載したpasswordを設定
- [x] config/database.ymlの`default`の`socket: /tmp/mysql.sock`をコメントアウト
- [x] config/database.ymlの`default`に、`host: db`を追記
- [x] config/webpacker.ymlの`development`の`check_yarn_integrity: true`を`false`に変更
- [x] `docker-compose run --rm app rails db:create`を実行
- [x] `docker-compose run --rm app rails db:migrate`を実行
- [x] `docker-compose up`でサーバーを起動できることを確認
- [x] Sequel ProでDBにアクセスし、本番環境からデータをインポート
- [x] デプロイして本番環境に影響がないことを確認

**Comment by nobmurakami** [comment]
完了
